---
- name: Configure rsyslogd.
  ansible.builtin.template:
    src: etc/rsyslog/al-remote.conf
    dest: /etc/rsyslog.d/al-remote.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart rsyslog.
  tags: rsyslog
