---

- name: Configure rsyslogd
  ansible.builtin.template:
    src: templates/etc/rsyslog/al-remote.conf
    dest: /etc/rsyslog.d/al-remote.conf
    owner: root
    group: root
    mode: 0644
  when: rsyslog_init is success
  notify:
    - restart rsyslog
  tags: rsyslog
