---
- name: Insert/Update syslog-ng.conf for inclusion of al-remote.conf.
  ansible.builtin.lineinfile:
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: /etc/syslog-ng/conf.d/al-remote.conf
    line: "include '/etc/syslog-ng/conf.d/al-remote.conf';"
  notify:
    - Reload syslog-ng.
  tags: syslog_ng

- name: Ensure al-remote.conf file is in place for syslog-ng.
  ansible.builtin.template:
    src: etc/syslog-ng/al-remote.conf
    dest: /etc/syslog-ng/conf.d/al-remote.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload syslog-ng.
  tags: syslog_ng
