---

- name: Set Linux optional facts
  ansible.builtin.set_fact:
    al_remote_provision_options: []

- name: Set Linux optional fact for using a registration key
  ansible.builtin.set_fact:
    al_remote_provision_options: "{{ al_remote_provision_options  +  [ \"--key \" +  al_remote_registration_key  ] }}"
  when: al_remote_registration_key is defined and al_remote_registration_key != "your_registration_key_here"

- name: Provision Alert Logic Collector
  ansible.builtin.command: "/etc/init.d/al-log-syslog provision --key {{ al_remote_provision_options | join(' ') }}"
  notify:
    - restart al-log-syslog
  tags: provision_al_collector
  when: not al_remote_for_imaging and not collector_provisioned.stat.exists and al_remote_provision_options != "[]"

- name: Provision Alert Logic Collector - for Imaging
  ansible.builtin.command: "/etc/init.d/al-log-syslog provision --key {{ al_remote_provision_options | join(' ') }}"
  tags: provision_al_collector
  when: al_remote_for_imaging and not collector_provisioned.stat.exists and al_remote_provision_options != "[]"
