---

- name: Provision Alert Logic Collector
  ansible.builtin.command: "/etc/init.d/al-log-syslog provision --key {{ al_remote_registration_key }}"
  notify:
    - restart al-log-syslog
  tags: provision_al_collector
