---
- name: Restart al-log-syslog.
  ansible.builtin.service:
    name: al-log-syslog
    state: restarted

- name: Reload syslog-ng.
  ansible.builtin.service:
    name: syslog-ng
    state: reloaded

- name: Restart rsyslog.
  ansible.builtin.service:
    name: rsyslog
    state: restarted
